#!/bin/bash

sudo apt update -y
sudo apt install nginx -y
ip=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)
echo "<h2>Hello AWS and Teraform!</h2> <br> IP: $ip" > /var/www/html/index.html
sudo service nginx restart
systemctl nginx enable

